apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: golang-greetings-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shamimice03/ArgoCD-with-demo.git
    targetRevision: HEAD
    path: application-manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: greetings-app
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
   
    automated:
       prune: true
       selfHeal: true
  
  